### PR TITLE
Dockerize project and reduce dependency list

### PR DESCRIPTION
**Pull request by tanertopal**
I have added a Dockerfile and modified the KAICD.yml to be as minimal as possible. Also upgraded some packages to ensure GPU enabled packages are downloaded for the CUDA version of the Docker container. I also added a guide to the README.md. Let me know if there are any questions. Feel free to adjust anything.

### CODE REVIEW

**Comment by sooheon** [comment]
Looks great, love that the scripts handle docker -v args. Thanks!

**Comment by sooheon** [comment]
@tanertopal Fixed a small bug in dev script. Any tips on how to connect the running dev env to editor?

**Comment by tanertopal** [comment]
@sooheon with the dev.sh script your local directory should be mounted into the docker container under the `/app` path. Your changes on the host system will edit the same file in the docker container. You can simple open e.g. VS Code and edit the project and the changes should be reflected in the docker container environment. Does this help?

Thank you for the bugfix! Good catch.

**Comment by sooheon** [comment]
@tanertopal That makes sense for i.e. editing files and then running scripts w/ docker bash. How do you use the in-docker env integrated to your editor (i.e. intellisense, running files/code inline)?

**Comment by tanertopal** [comment]
@sooheon the `dev.sh` setup / approach here is mostly for debugging.

In general we use poetry / pyproject.toml and locally in a venv installed projects. In cases like this project or when we have to run the project in a container locally or remote its an option to start the ssh daemon in the Docker container and use e.g. VS Code remote development in the container (beware that some extensions for VS Code do not work when doing remote development).

Are you interested in generally working in a unified environment or to work in the container in the scope of this project?

Here an example how to enable any container for remote development.

**Install and configure openssh-server**

```Dockerfile
# Install openssh-server
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssh-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Configure SSH daemon
RUN mkdir /var/run/sshd
ARG ssh_password=flower
RUN echo "root:${ssh_password}" | chpasswd
RUN sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config

# Expose SSH port
EXPOSE 22

# Set ssh daemon as process 0
CMD ["/usr/sbin/sshd", "-D"]
```

**Start the container**

```bash
docker run my_image -p 2222:22
```

**Use a SSH config similar to this for VS Code**

```text
Host docker
  HostName localhost
  Port 2222
  User root
```

Afterwards use VS Code Remote SSH extension if you are using VS Code.

**Pull request merged**
